<a href="https://colab.research.google.com/github/HEMA1188/Task2-GuviGeekNumpy/blob/main/GuviNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [ ]:
import numpy as np


2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)

1.21.6


3. Create a null vector of size 10 (★☆☆)

In [ ]:
def null_array(n):
  x=np.zeros(n)
  return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [ ]:
x = np.array([10,20,34])
 
print("Size of the array: ",
      x.size)
 
print("Memory size of one array element in bytes: ",
      x.itemsize)
 
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24



5. How to get the documentation of the numpy add function from the command line?

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out


6. create **null** vector of size 10 but fifth value which is 1


In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]



7. Create a vector with values ranging from 10 to 49 

In [ ]:
import numpy as np
a = np.arange(15,55)
print(a)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Reverse the vector first element become last

In [ ]:
x=[1,3,5,7,2,8]
print(x[::-1])

[8, 2, 7, 5, 3, 1]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [ ]:
A = [1,2,0,0,4,0]
print(np.nonzero(A))



(array([0, 1, 4]),)



11. Create a 3x3 identity matrix 

In [ ]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values 

In [ ]:
x=np.random.random((3,3,3))
print(x)

[[[0.09948711 0.14499651 0.87422892]
  [0.11363473 0.02464603 0.89728525]
  [0.37445922 0.56515148 0.34413267]]

 [[0.12729746 0.1198444  0.60260184]
  [0.39168939 0.35470654 0.59048991]
  [0.2762484  0.13979391 0.02340702]]

 [[0.92884476 0.93478104 0.84677492]
  [0.98871923 0.93077288 0.57066861]
  [0.41029768 0.85629194 0.444458  ]]]



13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
import numpy as np
n=np.random.random((10,10))
print(n)
print(n.min())
print(n.max())


[[0.77839744 0.90555511 0.82648896 0.56269095 0.50880658 0.8986838
  0.66807648 0.25038537 0.23544899 0.84850692]
 [0.68016286 0.8668934  0.42923297 0.69389752 0.6918459  0.65749498
  0.62382519 0.54656954 0.47919589 0.12118336]
 [0.64657639 0.85675969 0.42903151 0.56554406 0.9530148  0.82082749
  0.13778758 0.96009137 0.7069983  0.77038493]
 [0.29231861 0.27281411 0.18249347 0.66346576 0.18906098 0.96679095
  0.52395519 0.80077373 0.46614747 0.81445614]
 [0.67668074 0.82211026 0.06501043 0.89647538 0.83401556 0.92473517
  0.42851829 0.76541607 0.41810642 0.25310124]
 [0.70089649 0.71844042 0.93703869 0.56228067 0.25363257 0.63603368
  0.27841111 0.99283753 0.56218757 0.77463475]
 [0.23136942 0.09193014 0.18920125 0.91635879 0.51775058 0.74357065
  0.75097935 0.21389088 0.49541629 0.95058889]
 [0.22171353 0.84277347 0.78656451 0.15382492 0.06878879 0.94070844
  0.41284161 0.67024012 0.66709285 0.41274329]
 [0.95627451 0.73862329 0.96714936 0.0749799  0.15377508 0.99333195
  0.29683792 

14. Create a random vector of size 30 and find the mean value

In [ ]:
x=np.random.random((30,30))
print(x.mean())

0.4933228040873684


15. Create a 2d array with 1 on the border and 0 inside 

In [ ]:
import numpy as np
border=np.ones((5,5), dtype=int)
border[1:-1,1:-1]=0
print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array? 

In [ ]:

x=np.ones((3,3))
print(x)
y=np.pad(x,1)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17.What is the result of the following expression?


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [ ]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
array= np.array([[0,1], [1,0]])
x = np.tile(array,(4,4))
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.



24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.77279626 0.33281194 0.96520537]
 [0.26994687 0.71758744 0.70336807]
 [0.84829633 0.02107089 0.0732987 ]
 [0.92334841 0.51534486 0.56205603]
 [0.3576916  0.14010334 0.42602337]]
Second array:
[[0.63364672 0.34107255]
 [0.84892767 0.51128181]
 [0.73423662 0.8800726 ]]
Dot product of two arrays:
[[1.48090221 1.28319109]
 [1.29666937 1.07797584]
 [0.60922644 0.36461193]
 [1.43524933 1.07306537]
 [0.65838967 0.56856257]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [ ]:
x = np.arange(11)
y=x[(x >= 3) & (x <= 8)] = -1
y

-1

26. What is the output of the following script?

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider integer vector Z, which of these expression as legel?





In [ ]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

28.what are the result of following expression?

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

29. How to round away from zero a float array ? 

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-6., -4., -4., -3.,  5., 10.,  9., -3., -6., -2.])

30. How to find common values between two arrays? 

In [ ]:

import numpy as np
    
a1 = np.array([0, 1, 2, 3, 4])
a2 = [1, 3, 4]
  
# Common values between two arrays
print(np.intersect1d(a1, a2))

[1 3 4]


31. How to ignore all numpy warnings (not recommended)?

In [ ]:
import numpy as np
data = np.random.random(100000).reshape(10, 100, 100) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:997: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanmedian1d, axis, a, overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

32. Is the following expressions true? false

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False


33.How to get the dates of yesterday, today and Tomorrow?

In [ ]:

import numpy as np
  
# for today
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for yesterday
yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D')
  
print("Yesterday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D')+ np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)

Today:  2022-10-27
Yesterday:  2022-10-26
Tomorrow:  2022-10-28



34. How to get all the dates corresponding to the month of July 2016?

In [ ]:
import numpy as np
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))


July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']



35. How to compute ((A+B)*(-A/2)) in place (without copy)?


In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array using 5 different methods

In [ ]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([ 7.,  4., -8., -8.,  1.,  5.,  0., -7., -3.,  7.])

 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])


 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [ ]:
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

40. Create a random vector of size 10 and sort it (★★☆)


In [ ]:
x = np.random.random(size=10)
x.sort()


41. How to sum a small array faster than np.sum? (★★☆)


In [ ]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

6.775379180908203
4.526376724243164


42. Consider two random array A and B, check if they are equal (★★☆)


In [ ]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True


43. Make an array immutable (read-only) (★★☆)


In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1   # ValueError: assignment destination is read-only

ValueError: ignored

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [ ]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.82015553 0.71320106 0.58621921 0.40307222 0.97443062 0.50937958
 0.45851817 0.85970525 0.50491191 0.46403625]
[0.84106245 0.26742188 1.05387303 1.32895421 1.24448859 1.3993925
 1.55196898 1.37889809 0.55289804 0.01404094]


 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [ ]:
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0

46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)


In [ ]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


In [ ]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[-6.46870941e+04, -6.56099172e+03, -1.89502036e+04,
        -3.88437226e+04, -3.72650883e+04],
       [ 1.64708432e+04, -3.35351552e+04,  8.96600978e+06,
         3.77419278e+06,  1.02215711e+06],
       [-2.13539172e+04,  6.00340583e+06,  1.29434399e+06,
         8.54458324e+03, -4.44435700e+04],
       [-3.73052763e+04, -1.80366051e+04, -2.17844515e+05,
        -3.70418696e+04, -8.89467066e+06],
       [-1.72345666e+05, -2.63777901e+07,  9.77693802e+03,
         5.58364213e+04,  4.94341955e+04]])

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973



48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

13



51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         1.08792252 0.80302509 0.95898092 0.55361162 1.002452
  0.04613512 0.19877435 0.31426409 0.61511332]
 [1.08792252 0.         0.29570973 0.86112268 0.75038417 0.29301002
  1.05206427 0.94098235 0.8560641  0.56763044]
 [0.80302509 0.29570973 0.         0.6812998  0.56360246 0.37361743
  0.76491326 0.64740905 0.56038583 0.28265091]
 [0.95898092 0.86112268 0.6812998  0.         1.09847832 1.04998556
  0.91374273 0.764461   0.65612048 0.49801063]
 [0.55361162 0.75038417 0.56360246 1.09847832 0.         0.54726453
  0.54581324 0.54918979 0.5677262  0.60270169]
 [1.002452   0.29301002 0.37361743 1.04998556 0.54726453 0.
  0.97581034 0.90041573 0.84576265 0.63691624]
 [0.04613512 1.05206427 0.76491326 0.91374273 0.54581324 0.97581034
  0.         0.15264115 0.26815263 0.57092708]
 [0.19877435 0.94098235 0.64740905 0.764461   0.54918979 0.90041573
  0.15264115 0.         0.11587114 0.42832132]
 [0.31426409 0.8560641  0.56038583 0.65612048 0.5677262  0.84576265
  0.26815263 0.1158711

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[10 23  4 45  2 64 44 58 76 67]


54. How to read the following file? (★★☆)

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.05073168  0.25395257 -0.16097339 -0.15045441  0.00454556 -0.1308721
   0.33714717 -0.18577457 -0.16550801  0.14720552]
 [-0.33254868  0.02682566 -0.19712082 -0.09494742 -0.38606476  0.12304507
  -0.18572122  0.39756394  0.44522873  0.20373948]
 [-0.57262924  0.0985585  -0.17517214 -0.15504177  0.25451746  0.14360688
  -0.1774597   0.1402626   0.11366346  0.32969395]
 [ 0.12914252 -0.45202709  0.40607569 -0.02306651 -0.00967082  0.26117686
  -0.42065921 -0.02634231  0.04425312  0.09111776]
 [ 0.35672727 -0.13370738 -0.29578851  0.43230138  0.23782897  0.10419148
  -0.05002361 -0.15178357 -0.27927017 -0.22047586]]


 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 9 9]
 [9 7 4]
 [0 0 2]]
[[0 0 2]
 [9 7 4]
 [7 9 9]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


 61. Find the nearest value from a given value in an array (★★☆)


In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5156112207430259



62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

---



In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute (★★☆

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)



In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 3. 1. 1. 4. 3. 4. 2. 4. 4.]
[7. 5. 1. 1. 7. 5. 7. 3. 7. 7.]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)



In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)



In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[65 70 53 66]
 [51 66 59 58]
 [71 59 60 59]]
[[65 70 53 66]
 [51 66 59 58]
 [71 59 60 59]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.52533644 0.42255122 0.38989897 0.61914    0.55538298 0.66982728
 0.56334774 0.42139414 0.51851377 0.4450034 ]
0    0.525336
1    0.422551
2    0.389899
3    0.619140
4    0.555383
5    0.669827
6    0.563348
7    0.421394
8    0.518514
9    0.445003
dtype: float64


 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.31859745, 2.32799715, 1.34449248, 1.64687858, 1.13526486])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [ ]:

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)



In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 37) ( 1, 69) ( 6, 44) ( 6, 67) (20, 29) (20, 92) (26, 30) (26, 60)
 (29, 92) (30, 60) (31, 37) (31, 96) (33, 47) (33, 60) (36, 61) (36, 86)
 (37, 69) (37, 96) (40, 78) (40, 91) (41, 41) (41, 79) (44, 67) (47, 60)
 (61, 86) (64, 94) (64, 99) (78, 91) (94, 99)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


75. How to compute averages using a sliding window over an array? (★★★)


In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.7261355 ,  0.99602671, -0.28878638,  0.77734343,  0.92685911,
        0.94412806,  0.94240722, -0.13471739,  0.56202336, -0.12661819,
       -0.73933644,  0.04753515,  0.70532254,  0.12181271, -0.47772525,
       -0.37049332,  0.09640564, -0.78035053,  0.56187218, -0.5065446 ,
        0.8708823 , -0.43012282, -0.70148393,  0.49693705, -0.26918738,
       -0.71913636,  0.04430685, -0.76093016,  0.08636918,  0.920767  ,
        0.11369584,  0.00187445,  0.73087213,  0.24719248, -0.92599513,
       -0.33030362, -0.71527752, -0.76416804,  0.76077194,  0.80803417,
        0.36373705,  0.75322721,  0.73809728,  0.7554498 ,  0.34164398,
       -0.19751605, -0.58300513, -0.88819996,  0.46321746,  0.1216422 ,
       -0.50400754, -0.81029623, -0.08339185, -0.72226975,  0.98647058,
       -0.13796184, -0.34060929,  0.30608351,  0.84230598, -0.46966928,
       -0.70303898, -0.49592939,  0.34280469, -0.39732265, -0.39443793,
        0.22675894,  0.81001159,  0.65025954, -0.67737274,  0.14

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[ 8.30224785  5.13373774  3.58515206  0.16947476  3.05372623  2.45219302
 10.02714095  4.25388487  4.49275137  6.68537311]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)



In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.11394769e+00 3.26957649e+00 1.85386774e-01 2.87112557e+00
  1.12722500e+01 1.44092354e+01 3.71596004e+00 2.42048217e+00
  7.41070412e+00 1.30975836e+00]
 [1.18017910e+01 7.21102698e+00 1.26350587e+01 8.47633426e+00
  1.02344011e+00 3.88879108e+00 6.99690348e+00 8.57778506e+00
  1.74140991e+01 1.67156650e+00]
 [2.96929482e+00 1.02069579e+01 1.54887498e+00 8.84454365e+00
  6.29975481e+00 9.74720595e+00 7.12802113e-01 1.63868135e+00
  4.74385934e-02 1.13005136e+01]
 [8.47076042e+00 1.19167336e+01 5.35236440e+00 1.14755204e+01
  1.39333149e+01 1.73588211e+01 6.87650262e+00 5.90556067e+00
  1.20834586e+00 7.72135071e+00]
 [3.29747980e-01 5.40757431e-02 3.90933544e-01 3.16733699e-02
  1.25518104e+01 1.55562883e+01 4.76412753e+00 3.31309562e+00
  1.07589192e+01 2.62184818e+00]
 [2.72111815e+00 6.86018376e+00 7.77132500e+00 4.86120094e+00
  2.76604188e-01 3.66788276e+00 6.82879545e+00 7.80354244e+00
  3.06829225e+00 1.22241255e+01]
 [1.18265769e+01 4.41377179e+00 1.42937584e+01 6.24531525e

 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 7 5 8 0 2 0 8 6 4]
 [0 9 4 5 6 9 1 7 8 8]
 [6 6 5 5 1 0 7 5 3 0]
 [8 9 8 8 1 8 3 7 2 1]
 [6 2 5 7 5 4 6 2 3 1]
 [5 1 0 0 8 4 6 1 0 5]
 [5 1 7 8 0 3 3 0 3 9]
 [4 6 7 8 2 4 0 1 8 4]
 [5 7 0 9 5 1 0 0 0 8]
 [2 5 2 9 9 6 3 0 2 3]]
[[0 0 0 0 0]
 [0 5 7 5 8]
 [0 0 9 4 5]
 [0 6 6 5 5]
 [0 8 9 8 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

---



In [ ]:

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


 83. How to find the most frequent value in an array?


In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 3 0]
   [3 2 4]
   [2 0 0]]

  [[3 0 1]
   [2 4 2]
   [0 0 3]]

  [[0 1 0]
   [4 2 0]
   [0 3 1]]

  [[1 0 2]
   [2 0 0]
   [3 1 3]]

  [[0 2 2]
   [0 0 0]
   [1 3 4]]

  [[2 2 2]
   [0 0 2]
   [3 4 3]]

  [[2 2 2]
   [0 2 3]
   [4 3 1]]

  [[2 2 3]
   [2 3 3]
   [3 1 2]]]


 [[[3 2 4]
   [2 0 0]
   [1 3 4]]

  [[2 4 2]
   [0 0 3]
   [3 4 4]]

  [[4 2 0]
   [0 3 1]
   [4 4 4]]

  [[2 0 0]
   [3 1 3]
   [4 4 4]]

  [[0 0 0]
   [1 3 4]
   [4 4 3]]

  [[0 0 2]
   [3 4 3]
   [4 3 4]]

  [[0 2 3]
   [4 3 1]
   [3 4 0]]

  [[2 3 3]
   [3 1 2]
   [4 0 2]]]


 [[[2 0 0]
   [1 3 4]
   [3 2 3]]

  [[0 0 3]
   [3 4 4]
   [2 3 2]]

  [[0 3 1]
   [4 4 4]
   [3 2 1]]

  [[3 1 3]
   [4 4 4]
   [2 1 1]]

  [[1 3 4]
   [4 4 3]
   [1 1 2]]

  [[3 4 3]
   [4 3 4]
   [1 2 0]]

  [[4 3 1]
   [3 4 0]
   [2 0 3]]

  [[3 1 2]
   [4 0 2]
   [0 3 3]]]


 [[[1 3 4]
   [3 2 3]
   [4 2 3]]

  [[3 4 4]
   [2 3 2]
   [2 3 1]]

  [[4 4 4]
   [3 2 1]
   [3 1 4]]

  [[4 4 4]
   [2 1 1]
   [1 4 4]]

  [[4 4 3]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  4  4 11 10]
 [ 4  2 14  9 12]
 [ 4 14  6 42  3]
 [11  9 42  7 12]
 [10 12  3 12  5]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:


Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))


Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays? (★★★)


In [ ]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


89. How to get the n largest values of an array (★★★)


In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.11 s ± 8.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
57.4 ms ± 930 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.5 ms ± 586 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)



In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 7]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 4]
 [2 3 4]
 [0 3 4]
 [1 1 3]
 [3 2 3]
 [3 0 2]
 [3 0 1]
 [2 0 4]
 [4 3 1]
 [4 1 0]]
[[1 1 4]
 [2 3 4]
 [0 3 4]
 [1 1 3]
 [3 2 3]
 [3 0 2]
 [3 0 1]
 [2 0 4]
 [4 3 1]
 [4 1 0]]
[[1 1 4]
 [2 3 4]
 [0 3 4]
 [1 1 3]
 [3 2 3]
 [3 0 2]
 [3 0 1]
 [2 0 4]
 [4 3 1]
 [4 1 0]]


95. Convert a vector of ints into a matrix binary representation (★★★)



In [ ]:

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.19236502, 0.15619119, 0.21052369, 0.28737125, 0.10378904,
        0.31454926, 0.1566749 , 0.15977875, 0.19260572, 0.29797378],
       [0.57038021, 0.46312144, 0.62422236, 0.85208253, 0.30774418,
        0.93266785, 0.46455567, 0.47375888, 0.57109392, 0.88352002],
       [0.4086168 , 0.33177729, 0.44718898, 0.61042658, 0.220466  ,
        0.66815739, 0.33280477, 0.33939789, 0.4091281 , 0.6329482 ],
       [0.3328651 , 0.27027053, 0.36428655, 0.49726223, 0.17959476,
        0.54429058, 0.27110753, 0.27647838, 0.33328161, 0.51560867],
       [0.36515547, 0.29648877, 0.39962503, 0.54550034, 0.19701678,
        0.59709078, 0.29740696, 0.30329882, 0.36561238, 0.56562651],
       [0.06818469, 0.05536271, 0.07462112, 0.1018601 , 0.03678852,
        0.11149347, 0.05553416, 0.05663433, 0.06827001, 0.10561822],
       [0.13836587, 0.11234646, 0.15142718, 0.20670272, 0.07465422,
        0.22625153, 0.11269439, 0.11492695, 0.138539  , 0.21432899],
       [0.55960453, 0.45437211, 0.6124294

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)



In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14377962  0.22543739]
